### ISSUE TITLE
Fails when the length of JSON has approx  65500

### ISSUE THREAD

**Issue by ibnishak** [qrtz/nativemessaging#2]
Minimal test case

```go
package main

import (
	"fmt"
	"io"
	"os"

	"github.com/qrtz/nativemessaging"
)

func main() {

	decoder := nativemessaging.NewNativeJSONDecoder(os.Stdin)

	for {
		var msg message
		err := decoder.Decode(&msg)

		if err != nil {
			if err == io.EOF {
				return
			}
		} else {
			fmt.Println(msg.Content)
		}

	}
}

type message struct {
	Content string `json:"content"`
}
```

This works well until when the JSON has approx 65500 characters. 

Any other logs I need to provide?

**Comment by qrtz** [comment]
I'm unable to reproduce this issue with even larger JSON payloads.  
Do you have more information such as log, error messages?

**Comment by ibnishak** [comment]
OS: Arch Linux

stderr:

```
  fatal error: runtime: out of memory
  
  runtime stack:
  runtime.throw(0x4f78fe, 0x16)
  	/usr/lib/go/src/runtime/panic.go:608 +0x72
  runtime.sysMap(0xc0e8000000, 0x8c000000, 0x5d45f8)
  	/usr/lib/go/src/runtime/mem_linux.go:156 +0xc7
  runtime.(*mheap).sysAlloc(0x5bbf60, 0x8c000000, 0x0, 0xc00004be30)
  	/usr/lib/go/src/runtime/malloc.go:619 +0x1c7
  runtime.(*mheap).grow(0x5bbf60, 0x44580, 0x0)
  	/usr/lib/go/src/runtime/mheap.go:920 +0x42
  runtime.(*mheap).allocSpanLocked(0x5bbf60, 0x44580, 0x5d4608, 0x0)
  	/usr/lib/go/src/runtime/mheap.go:848 +0x337
  runtime.(*mheap).alloc_m(0x5bbf60, 0x44580, 0xffffffffffff0101, 0xc00004bf10)
  	/usr/lib/go/src/runtime/mheap.go:692 +0x119
  runtime.(*mheap).alloc.func1()
  	/usr/lib/go/src/runtime/mheap.go:759 +0x4c
  runtime.(*mheap).alloc(0x5bbf60, 0x44580, 0xc000010101, 0x422d70)
  	/usr/lib/go/src/runtime/mheap.go:758 +0x8a
  runtime.largeAlloc(0x88affffc, 0x440101, 0xc07dbfc000)
  	/usr/lib/go/src/runtime/malloc.go:1019 +0x97
  runtime.mallocgc.func1()
  	/usr/lib/go/src/runtime/malloc.go:914 +0x46
  runtime.systemstack(0x0)
  	/usr/lib/go/src/runtime/asm_amd64.s:351 +0x66
  runtime.mstart()
  	/usr/lib/go/src/runtime/proc.go:1229
  
  goroutine 1 [running]:
  runtime.systemstack_switch()
  	/usr/lib/go/src/runtime/asm_amd64.s:311 fp=0xc0000b48b8 sp=0xc0000b48b0 pc=0x44fd10
  runtime.mallocgc(0x88affffc, 0x4cf120, 0x1, 0xc0000b4990)
  	/usr/lib/go/src/runtime/malloc.go:913 +0x896 fp=0xc0000b4958 sp=0xc0000b48b8 pc=0x40b0c6
  runtime.makeslice(0x4cf120, 0x88affffc, 0x88affffc, 0xc07dbfc000, 0x4457fffc, 0x4457fffc)
  	/usr/lib/go/src/runtime/slice.go:70 +0x77 fp=0xc0000b4988 sp=0xc0000b4958 pc=0x43bf17
  bytes.makeSlice(0x88affffc, 0x0, 0x0, 0x0)
  	/usr/lib/go/src/bytes/buffer.go:231 +0x6d fp=0xc0000b49c8 sp=0xc0000b4988 pc=0x46200d
  bytes.(*Buffer).grow(0xc00008c000, 0x4, 0x4)
  	/usr/lib/go/src/bytes/buffer.go:144 +0x15a fp=0xc0000b4a18 sp=0xc0000b49c8 pc=0x46197a
  bytes.(*Buffer).WriteString(0xc00008c000, 0x4f4b67, 0x4, 0x0, 0x0, 0x0)
  	/usr/lib/go/src/bytes/buffer.go:186 +0xdc fp=0xc0000b4a48 sp=0xc0000b4a18 pc=0x461d7c
  encoding/json.(*encodeState).string(0xc00008c000, 0xc0000b8000, 0x395578a6, 0xc0000b8001)
  	/usr/lib/go/src/encoding/json/encode.go:915 +0x126 fp=0xc0000b4aa8 sp=0xc0000b4a48 pc=0x4b4666
  encoding/json.stringEncoder(0xc00008c000, 0x4cefe0, 0xc000082060, 0x98, 0x100)
  	/usr/lib/go/src/encoding/json/encode.go:610 +0xdc fp=0xc0000b4b70 sp=0xc0000b4aa8 pc=0x4b1b4c
  encoding/json.(*structEncoder).encode(0xc00007a240, 0xc00008c000, 0x4ddec0, 0xc000082060, 0x99, 0x4d0100)
  	/usr/lib/go/src/encoding/json/encode.go:647 +0x280 fp=0xc0000b4cd0 sp=0xc0000b4b70 pc=0x4b2380
  encoding/json.(*structEncoder).encode-fm(0xc00008c000, 0x4ddec0, 0xc000082060, 0x99, 0xc0000b0100)
  	/usr/lib/go/src/encoding/json/encode.go:661 +0x64 fp=0xc0000b4d10 sp=0xc0000b4cd0 pc=0x4ba134
  encoding/json.(*encodeState).reflectValue(0xc00008c000, 0x4ddec0, 0xc000082060, 0x99, 0x4d0100)
  	/usr/lib/go/src/encoding/json/encode.go:333 +0x82 fp=0xc0000b4d48 sp=0xc0000b4d10 pc=0x4afcb2
  encoding/json.(*encodeState).marshal(0xc00008c000, 0x4ddec0, 0xc000082060, 0x100, 0x0, 0x0)
  	/usr/lib/go/src/encoding/json/encode.go:305 +0xf4 fp=0xc0000b4d90 sp=0xc0000b4d48 pc=0x4af764
  encoding/json.Marshal(0x4ddec0, 0xc000082060, 0x39557801, 0x1000039557872, 0x8, 0x18, 0xc000082060)
  	/usr/lib/go/src/encoding/json/encode.go:160 +0x52 fp=0xc0000b4e08 sp=0xc0000b4d90 pc=0x4af202
  github.com/qrtz/nativemessaging.Encode(0x50ecc0, 0xc000092008, 0x4ddec0, 0xc000082060, 0x50f080, 0x5d3708, 0xc0000b4f70, 0xc000082060, 0xc000082060)
  	/home/richie/Repos/Go/src/github.com/qrtz/nativemessaging/messaging.go:232 +0x3f fp=0xc0000b4e78 sp=0xc0000b4e08 pc=0x4bb85f
  github.com/qrtz/nativemessaging.(*jsonEncoder).Encode(0xc000082040, 0x4ddec0, 0xc000082060, 0xc000082060, 0xc000078210)
  	/home/richie/Repos/Go/src/github.com/qrtz/nativemessaging/messaging.go:124 +0x5d fp=0xc0000b4ed0 sp=0xc0000b4e78 pc=0x4bb05d
  main.main()
  	/home/richie/Timimi/timimi.go:41 +0x1ea fp=0xc0000b4f98 sp=0xc0000b4ed0 pc=0x4bbf1a
  runtime.main()
  	/usr/lib/go/src/runtime/proc.go:201 +0x207 fp=0xc0000b4fe0 sp=0xc0000b4f98 pc=0x429ba7
  runtime.goexit()
  	/usr/lib/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc0000b4fe8 sp=0xc0000b4fe0 pc=0x451c71
```

**Comment by ibnishak** [comment]
This happens whenever the json message exceed `pipe buffer max` limit in linux, which is 65330. The same addon works when the native host is written in [python](https://github.com/mdn/webextensions-examples/blob/master/native-messaging/app/ping_pong.py). 

I have set up a test. Try the following
```
git clone --branch qrtz --single-branch https://tesseract-index@bitbucket.org/tesseract-index/chrome-native-messaging-test-riz.git  && cd chrome-native-messaging-test-riz
./json2msg.js < test-not-working.json | go run main.go
./json2msg.js < test-working.json | go run main.go
```

**Comment by qrtz** [comment]
The problem seems to be with how the javascript is sending/encoding the data.
Try using the follow in lieu of the javascript file
```go
// json2msg.go

package main

import (
	"encoding/json"
	"io/ioutil"
	"log"
	"os"

	"github.com/qrtz/nativemessaging"
)

func main() {
	data, err := ioutil.ReadAll(os.Stdin)
	if err != nil {
		log.Fatal(err)
	}
	var msg message
	err = json.Unmarshal(data, &msg)
	if err != nil {
		log.Fatal(err)
	}
	encoder := nativemessaging.NewNativeJSONEncoder(os.Stdout)
	err = encoder.Encode(msg)
	if err != nil {
		log.Fatal(err)
	}
}

type message struct {
	Content string `json:"content"`
}
```
```
go run json2msg.go < test-not-working.json | go run main.go
```
